### ISSUE TITLE
Syntaxerror on Token "->" when using iterate

### ISSUE THREAD

**Issue by alepri** [dresden-ocl/dresdenocl#68]
```
-- @model{../model/simple.uml}
package org::dresdenocl::examples::simple

context Person
def: foobar =  Bag{5,5,5}->iterate(elem : OclAny, acc : Bag = Bag{} | Bag{}))

endpackage
```

Using the example above in the simple exampleproject shipped with DresdenOCL causes an error:
`Syntax error on token "-> (NAVIGATION_OPERATOR)", "EOF" expected`
The type is EMFText Problem

**Comment by lschuetze** [comment]
Okay, we have problem to parse the `iterate` constraint, when you are using a comma but semicolon. The constraint can be parsed when you write it like the following:
`def: foobar = Bag{5,5,5}->iterate(elem : Integer; acc : Bag = Bag{} | Bag{} )`
If you are using elem as OclAny it will complain, too. The type in the Bag is deduced to Integer.

I did not look up the standard, thought. But I see many definitions which show using a semicolon not a comma.

**Comment by lschuetze** [comment]
I have looked up the standard and iterate is defined as

``` ocl
collection->iterate( elem : Type; acc : Type = <expression> |
expression-with-elem-and-acc )
```

So I will close this as invalid.

**Comment by alepri** [comment]
Ouch, this is kinda disconcerting. I've actually looked up the standard(http://www.omg.org/spec/OCL/2.4/ Chap. 7.6.6 if somebody is interested), but didn't noticed the mix-up. Sorry for the inconvenience.
