### ISSUE TITLE
OCL2 Interpreter Not Visible

### ISSUE THREAD

**Issue by goshi-f-a** [dresden-ocl/dresdenocl#69]
I am learning Dresden OCL from the manual. When reach at section 3.3, it say....
3.3 OCL INTERPRETATION
Now we can start the interpretation. To open the OCL Interpreter we use the menu option
Dresden OCL2 > Open OCL2 Interpreter. The OCL Interpreter View should now be visible (cf.
Fig. 3.4).

However I could not find "Open OCL2 Interpreter" menu/option. Is it a bug ? or I have something missing ?
I am using LUNA. 
Please help.

**Comment by lschuetze** [comment]
![image](https://cloud.githubusercontent.com/assets/2911272/9354222/f93a2eb6-466e-11e5-9962-1bc5f39ab30c.png)
I have installed the latest Dresden OCL version from http://dresden-ocl.org/update/luna/latest and I can open the view. Its named a bit different but you should be able to mitigate this.
Did you use the very same version of Dresden OCL, as is 3.4.1 from latest luna update site? If so, what version of Dresden OCL are you using? Which version of Java are you using?

**Comment by goshi-f-a** [comment]
Thanks for the quick help
Initially I had installed the the latest that you did. Then I uninstalled
that and  reinstalled it from http://www.dresden-ocl.org/update/4.4/.
Now menu is visible. I am using java version "1.8.0_51".
Regards,

On Wed, Aug 19, 2015 at 3:39 PM, Lars Schütze notifications@github.com
wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/2911272/9354222/f93a2eb6-466e-11e5-9962-1bc5f39ab30c.png
> I have installed the latest Dresden OCL version from
> http://dresden-ocl.org/update/luna/latest and I can open the view. Its
> named a bit different but you should be able to mitigate this.
> Did you use the very same version of Dresden OCL, as is 3.4.1 from latest
> luna update site? If so, what version of Dresden OCL are you using? Which
> version of Java are you using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dresden-ocl/dresdenocl/issues/69#issuecomment-132535014
> .

## 

Dr Farooque Azam
Professor
College of E&ME (NUST)
HEC Approved Supervisor http://sc.hec.gov.pk/aphds/submit.asp?supid=3286
