### ISSUE TITLE
Dresdenocl Maven Central Repository 

### ISSUE THREAD

**Issue by hammadirshad** [dresden-ocl/dresdenocl#73]
I want to build standalone version which required dresdenocl dependencies  I can't find the dresdenocl release on Maven Central Repository and Sonatype Nexus Releases <a href="https://oss.sonatype.org/content/repositories/releases/ ">https://oss.sonatype.org/content/repositories/releases/ </a>.Can you provide me online Repository link of dresdenocl

**Comment by lschuetze** [comment]
Please see Issue #72. In order to build it on your own you have to `mvn install` Dresden OCL. Then, in a second step you should be able to build the standalone.

Working solutions are welcome.

**Comment by hammadirshad** [comment]
if you publish it in form of pom packaging parallel to eclipse-repository so I can easily add that path in repository of standalone pom.xml. you need to add simple one more repository with pom packaging
